ViewModels/SlideViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Bazaar.ViewModel
{
    public class SlideViewModel
    {
        public int Id { get; set; }
        [Required]
        public int Order { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]

        public string Link { get; set; }
        public string Title { get; set; }
        public string ImgPath { get; set; }
        public int? Price { get; set; }
    }
}

Areas/Admin/Controllers/SliderManageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Bazar.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Controller;
using Bazar.Domain.Entities;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace Bazar.Areas.Admin.Controllers
{
    [Area("admin")]
    public class SliderManageController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _appEnvironment;

        public SliderManageController(IUnitOfWork unitOfWork, IMapper mapper, IWebHostEnvironment appEnvironment)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {

            var slidesViewModel = _unitOfWork.CarouselSlides.GetCarouselSlides()
                .Select(s => _mapper.Map<CarouselSlideViewModel>(s));

            return View("SliderManagePage", slidesViewModel);

        }

        public IActionResult SlideForm(CarouselSlideViewModel viewModel)
        {

            if (viewModel.Id == 0)
            {

                var slides = _unitOfWork.CarouselSlides.GetCarouselSlides();
                if (slides.Count() > 0)
                    viewModel.Order = slides.Max(s => s.Order) + 1;
                else
                    viewModel.Order = 1;

            }
            else
            {
               var slideInDb = _unitOfWork.CarouselSlides.GetCarouselSlide(viewModel.Id);
               viewModel = _mapper.Map<CarouselSlideViewModel>(slideInDb);
            }

            return View("SlideForm", viewModel);

        }


        [HttpPost]
        public IActionResult Save(CarouselSlideViewModel viewModel, IFormFile uploadImage)
        {
            /* if (!ModelState.IsValid || uploadImage == null)
                 return View("SlideForm", viewModel);*/

            if (viewModel.Id == 0)
            {
                if (uploadImage.Length > 0)
                {
                    string ext = uploadImage.ContentType.ToLower();
                    if (ext == "image/jpg" || ext == "image/jpeg" || ext == "image/png")
                    {
                        viewModel.ImgPath = UploadedFile(uploadImage, @"\img\carousel");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Не верный формат изображения");
                    }
                }

                _unitOfWork.CarouselSlides.AddCarouselSlide(_mapper.Map<CarouselSlide>(viewModel));
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            else
            {
                viewModel.ImgPath = UploadedFile(uploadImage ,@"\img\carousel" );
                _unitOfWork.CarouselSlides.UpdateCarouselSlide(viewModel.Id, _mapper.Map<CarouselSlide>(viewModel));
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }

        }




        private string UploadedFile(IFormFile uploadImage, string folderPaath)
        {
            var uploadsFolder = _appEnvironment.WebRootPath + folderPaath;
            if (!Directory.Exists(uploadsFolder))
                Directory.CreateDirectory(uploadsFolder);

            string uniqueFileName = null;
            uniqueFileName = Guid.NewGuid() + "_" + uploadImage.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            var img = SixLabors.ImageSharp.Image.Load(uploadImage.OpenReadStream());
            img.Mutate(x => x.Resize(800, 400));
            img.Save(filePath);

            return folderPaath + uniqueFileName;

        }

    }

}

Controllers/Api/SlidesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using Bazar.Domain.Dto;
using Bazar.Domain.Entities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;

namespace Bazar.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class SlidesController : ControllerBase
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly ILogger<HomeController> _logger;


        public SlidesController(IUnitOfWork unitOfWork, IMapper mapper, IWebHostEnvironment appEnvironment, ILogger<HomeController> logger)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _appEnvironment = appEnvironment;
            _logger = logger;
        }


        //GET /api/Slides
        [HttpGet]
        public ActionResult<IEnumerable<CarouselSlideDto>> GetCarouselSlides()
        {
            try
            {
                return _unitOfWork.CarouselSlides.GetCarouselSlides().Select(s => _mapper.Map<CarouselSlideDto>(s)).ToList();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside GetCarouselSlides action: {ex.Message}");
                return null;
            }
        }

        [HttpDelete("{id}")]
        public ActionResult DeleteCarouselSlide(int id)
        {
            try
            {
                var faqItem = _unitOfWork.CarouselSlides.GetCarouselSlide(id);

                if (faqItem == null)
                {
                    _logger.LogError($"Slide with id: {id}, hasn't been found in db.");
                    return NotFound();
                }

                _unitOfWork.CarouselSlides.DeleteCarouselSlide(id);
                _unitOfWork.Complete();

                return NoContent();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside DeleteCarouselSlide action: {ex.Message}");
                return StatusCode(500, "Internal server error");
            }
        }

    }
}

Areas/Admin/Views/SliderManage/SlideForm.cshtml
@model Bazar.ViewModel.CarouselSlideViewModel
@if (Model.Id == 0)
{
    <h2 class="text-center">Новый слайд</h2>
}
else
{
    <h2  class="text-center">Редактировать слайд</h2>
}


<form asp-action="Save" asp-controller="SliderManage" asp-antiforgery="true" method="post" enctype="multipart/form-data" >
    <div>

        <input type="hidden" asp-for="Id">

        <div class="form-group">
            <label asp-for="Order"></label>
            <input class="form-control" type="text" asp-for="Order" />
            <span asp-validation-for="Order"></span>
        </div>

        <div class="form-group">
            <label asp-for="Title"></label>
            <input class="form-control" type="text" asp-for="Title" />
            <span asp-validation-for="Title"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea class="form-control"  asp-for="Description" type="text" rows="3"></textarea>
            <span asp-validation-for="Description"></span>
        </div>

        <div class="form-group">
            <label asp-for="Price"></label>
            <input class="form-control" type="text" asp-for="Price" />
            <span asp-validation-for="Price"></span>
        </div>

        @if (Model.Id != 0)
        {


            <img src="@Model.ImgPath" />
        }

        <input type="file" name="uploadImage" />

        <div class="form-group">
            <label asp-for="Link"></label>
            <input class="form-control" type="text" asp-for="Link" />
            <span asp-validation-for="Link"></span>
        </div>


        <div>
            <input type="submit" value="Save" />
        </div>
    </div>
</form>

Areas/Admin/Views/SliderManage/SliderManagePage.cshtml
@model IEnumerable<Bazar.ViewModel.CarouselSlideViewModel>


@{
    ViewData["Title"] = "SliderManagePage";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <partial name="_Carousel" model="@Model" />
    <a href=""></a>
</div>



<div class="row mt-4">
    <div class="col">
        <table id="tblCarousel" class="table table-bordered table-hover w-100">
            <thead>
            <tr>
                <th>№</th>
                <th>Порядок</th>
                <th>Заголовок</th>
                <th>Описание</th>
                <th>Удалить</th>
            </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
  
</div>
<div class="row mb-3 mt-3">
    <div class="col w-100"><a class="btn btn-success w-100" asp-controller="SliderManage" asp-action="SlideForm">Добавить слайд </a></div>
</div>


@section scripts
{

    <script>
        $(document).ready(function () {
            var t = $('#tblCarousel').DataTable({

                ajax: {
                    url: "/api/Slides",
                    dataSrc: ""
                },
                columnDefs: [
                    {
                        targets: 0
                    }
                ],
                order: [[1, 'asc']],
                columns: [
                    {
                        width: "5%",
                        data: "order"
                    },
                    {
                        width: "10%",
                        data: "order"
                    },
                    {
                        data: "title",
                        render: function (data,type,slide) {
                            return "<a href='/admin/SliderManage/SlideForm/" + slide.id + "' class=''>"  + data + "</a>";
                        }
                    },
                    {
                        data: "description"
                    },
                    {
                        data: "id",
                        render: function (data) {
                            return "<button class='btn btn-danger w-100 js-delete' data-data-id=" +
                                data +
                                "><i class='fa fa-trash' aria-hidden='true'></i></button>";
                        }
                    }
                ]
            });

            t.on('order.dt search.dt',
                function () {
                    t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                        cell.innerHTML = i + 1;
                    });
                }).draw();


            $('#tblCarousel').on('click',
                '.js-delete',
                function () {
                    var button = $(this);

                    bootbox.confirm("Вы уверены?",
                        function (result) {
                            if (result) {
                                $.ajax({
                                    url: "/api/Slides/" + button.attr("data-data-id"),
                                    method: "DELETE",
                                    success: function () {
                                        button.parents("tr").remove();
                                    }
                                });
                            }

                        });


                });

        });


    </script>


}