ViewModels/GamesViewModel.cs
using System.Collections.Generic;
using Bazaar.ViewModel;
using Bazar.Domain.Entities;


namespace Bazar.ViewModel
{
    public class GamesViewModel
    {

        public List<Game> Games { get; set; }
        public List<Genre> Genres { get; set; }
        public List<Game> DiscountGames { get; set; }
        public List<SlideViewModel> Slides { get; set; }
    }
}

Areas/Admin/Controllers/GamesManagerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Bazar.Domain.AdditionalClasses;
using Bazar.Domain.Entities;
using Bazar.Models;
using Bazar.ViewModel;
using Bazar.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace Bazar.Areas.Admin.Controllers
{
    [Area("admin")]
    public class GamesManagerController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _appEnvironment;

        public GamesManagerController(IUnitOfWork unitOfWork, IMapper mapper, IWebHostEnvironment appEnvironment)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            return View("GamesManagerPage");
        }

        public IActionResult GameForm(GameFormViewModel viewModel)
        {

            if (viewModel.Id == 0)
            {
                viewModel.AllGenres = _unitOfWork.Genres.GetGenres().Select(g => g.Name);
                viewModel.AllModest = _unitOfWork.Mode.GetModes().Select(m => m.Name);
                viewModel.AllPlatforms = _unitOfWork.Platform.GetPlatforms().Select(p => p.Name);

            }
            else
            {
                var gameInDb = _unitOfWork.Games.GetGame(viewModel.Id);
                viewModel = _mapper.Map<GameFormViewModel>(gameInDb);

                viewModel.AllGenres = _unitOfWork.Genres.GetGenres().Select(g => g.Name);
                viewModel.AllModest = _unitOfWork.Mode.GetModes().Select(m => m.Name);
                viewModel.AllPlatforms = _unitOfWork.Platform.GetPlatforms().Select(p => p.Name);

                viewModel.SelectedGenres = gameInDb.Genres.Select(g => g.Name);
                viewModel.SelectedModes = gameInDb.Modes.Select(m => m.Name);
                viewModel.SelectedPlatforms = gameInDb.Platforms.Select(p => p.Name);
                viewModel.PosterPath = gameInDb.MediaResources.MainImagePath;
                viewModel.VideoLink = gameInDb.MediaResources.VideoLink;
                viewModel.SystemRequirementsVM = _mapper.Map<SystemRequirementsViewModel>(gameInDb.SystemRequirements);

                

                string imagesPath = Tools.GetGalleryPathOfGame(viewModel.Slug);
                var appData = _appEnvironment.WebRootPath + imagesPath;
                var images = Directory.GetFiles(appData).Select(x => imagesPath + Path.GetFileName(x));

                viewModel.GalleryImages = images;
            }

            return View("GameForm", viewModel);

        }



        [HttpPost]
        public async Task<IActionResult> AddContentImage(IEnumerable<IFormFile> files)
        {

            var uploadsFolder = $"{_appEnvironment.WebRootPath}\\img\\content";
            var vOriginalDirectory = @"\img\content\";

            if (!Directory.Exists(uploadsFolder))
                Directory.CreateDirectory(uploadsFolder);

            string output = "";
            foreach (var img in files)
            {

                string ext = img.ContentType.ToLower();
                if (ext == "image/jpg" || ext == "image/jpeg" || ext == "image/png")
                {
                    string uniqueFileName = null;
                    uniqueFileName = Guid.NewGuid() + "_" + img.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    string returnPath = Path.Combine(vOriginalDirectory, uniqueFileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await img.CopyToAsync(fileStream);
                    }

                    output += "<li>" + returnPath + "</li>";
                }
                else
                {
                    output += "Не верный формат изображения файла : " + img.FileName;

                }

            }

            return Content(output);

        }


        [HttpPost]
        public IActionResult Save(GameFormViewModel viewModel)
        {
            /*
            *сделать валидацию картинок (атрибут)
            * https://stackoverflow.com/questions/56588900/how-to-validate-uploaded-file-in-asp-net-core
            *проверть уже сущ игру
            *проверить кривые имена игр
            *
            */

            if (!ModelState.IsValid)
            {
                viewModel.AllGenres = _unitOfWork.Genres.GetGenres().Select(g => g.Name);
                viewModel.AllModest = _unitOfWork.Mode.GetModes().Select(m => m.Name);
                viewModel.AllPlatforms = _unitOfWork.Platform.GetPlatforms().Select(p => p.Name);
                return View("GameForm", viewModel);
            }


            if (viewModel.Id == 0)//если игра новая
            {

                string slug = viewModel.Name.GenerateSlug();

                if (_unitOfWork.Games.GetGames().Any(g => g.Slug.Equals(slug))) //если такая игра уже есть
                {
                    viewModel.AllGenres = _unitOfWork.Genres.GetGenres().Select(g => g.Name);
                    viewModel.AllModest = _unitOfWork.Mode.GetModes().Select(m => m.Name);
                    viewModel.AllPlatforms = _unitOfWork.Platform.GetPlatforms().Select(p => p.Name);
                    ModelState.AddModelError("", "That game name is taken!");

                    return View("GameForm", viewModel);
                }


                var newGame = _mapper.Map<Game>(viewModel);
                newGame.Slug = slug;


                //media
                var mediaResources = new MediaResources();

                if (viewModel.Poster == null)
                    mediaResources.MainImagePath = @"/img/default.jpg";
                else
                    mediaResources.MainImagePath = UploadedFile(viewModel.Poster, Tools.GetImagesPathOfGame(newGame.Slug));


                mediaResources.GalleryPath = UploadedScreens(viewModel.Screens, Tools.GetGalleryPathOfGame(newGame.Slug));
                mediaResources.VideoLink = viewModel.VideoLink;

                newGame.MediaResources = mediaResources;
                //media


                newGame.Genres = _unitOfWork.Genres.GetGenres()
                    .Where(s => viewModel.SelectedGenres.Contains(s.Name)).ToList();


                newGame.Modes = _unitOfWork.Mode.GetModes()
                    .Where(s => viewModel.SelectedModes.Contains(s.Name)).ToList();


                newGame.Platforms = _unitOfWork.Platform.GetPlatforms()
                    .Where(s => viewModel.SelectedPlatforms.Contains(s.Name)).ToList();


                newGame.SystemRequirements = _mapper.Map<SystemRequirements>(viewModel.SystemRequirementsVM);
                newGame.DateAdded = DateTime.Now;

                _unitOfWork.Games.Add(newGame);
                _unitOfWork.Complete();

            }
            else
            {
                var gameIdDb = _unitOfWork.Games.GetGame(viewModel.Id);


                string slug = viewModel.Name.GenerateSlug();

                if (gameIdDb.Slug != slug)
                {
                    if (_unitOfWork.Games.GetGames().Any(g => g.Slug.Equals(slug))) //если такая игра уже есть
                    {
                        viewModel.AllGenres = _unitOfWork.Genres.GetGenres().Select(g => g.Name);
                        viewModel.AllModest = _unitOfWork.Mode.GetModes().Select(m => m.Name);
                        viewModel.AllPlatforms = _unitOfWork.Platform.GetPlatforms().Select(p => p.Name);
                        ModelState.AddModelError("", "That game name is taken!");

                        return View("GameForm", viewModel);
                    }
                }

                gameIdDb.Name = viewModel.Name;
                gameIdDb.Slug = slug;
                gameIdDb.Description = viewModel.Description;
                gameIdDb.OriginalPrice = viewModel.OriginalPrice;
                gameIdDb.FinalPrice = viewModel.FinalPrice;
                gameIdDb.Publisher = viewModel.Publisher;
                gameIdDb.Developer = viewModel.Developer;
                gameIdDb.Language = viewModel.Language;
                gameIdDb.ReleaseDate = viewModel.ReleaseDate;
                
                if(viewModel.Poster != null)
                    gameIdDb.MediaResources.MainImagePath = UploadedFile(viewModel.Poster, Tools.GetImagesPathOfGame(gameIdDb.Slug));


                if (viewModel.GalleryImages != null)
                {

                    var imgName = viewModel.GalleryImages.Select(i => Path.GetFileName(i));

                    var appData = _appEnvironment.WebRootPath + Tools.GetGalleryPathOfGame(gameIdDb.Slug);

                    foreach (var img in Directory.GetFiles(appData))
                    {
                        var name = Path.GetFileName(img);
                        if (!imgName.Contains(name))
                        {
                            System.IO.File.Delete(img);
                        }

                        //if(!viewModel.GalleryImages.Contains())
                    }
                }

                if(viewModel.Screens != null)
                    UploadedScreens(viewModel.Screens, Tools.GetGalleryPathOfGame(gameIdDb.Slug));


                gameIdDb.MediaResources.VideoLink = viewModel.VideoLink;


                gameIdDb.Genres = _unitOfWork.Genres.GetGenres()
                    .Where(s => viewModel.SelectedGenres.Contains(s.Name)).ToList();


                gameIdDb.Modes = _unitOfWork.Mode.GetModes()
                    .Where(s => viewModel.SelectedModes.Contains(s.Name)).ToList();


                gameIdDb.Platforms = _unitOfWork.Platform.GetPlatforms()

Controllers/Api/GamesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Bazar.Domain.Dto;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;

namespace Bazar.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class GamesController : ControllerBase
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly ILogger<HomeController> _logger;


        public GamesController(IUnitOfWork unitOfWork, IMapper mapper, IWebHostEnvironment appEnvironment, ILogger<HomeController> logger)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _appEnvironment = appEnvironment;
            _logger = logger;
        }

        //GET /api/Slides
        [HttpGet]
        public ActionResult<IEnumerable<GameDto>> GetGames()
        {
            try
            {
                return _unitOfWork.Games.GetGames().Select(s => _mapper.Map<GameDto>(s)).ToList();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside GetGames action: {ex.Message}");
                return null;
            }
        }

        [HttpDelete("{id}")]
        public ActionResult DeleteGame(int id)
        {
            try
            {
                var gameItem = _unitOfWork.Games.GetGame(id);

                if (gameItem == null)
                {
                    _logger.LogError($"GAme with id: {id}, hasn't been found in db.");
                    return NotFound();
                }

                _unitOfWork.Games.Remove(gameItem);
                _unitOfWork.Complete();

                return NoContent();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside DeleteCarouselSlide action: {ex.Message}");
                return StatusCode(500, "Internal server error");
            }
        }

    }




}

Areas/Admin/Views/GamesManager/GamesManagerPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<table id="tblCarousel" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Origin Price</th>
        <th>Final Price</th>
        <th>Quantity</th>
        <th>Data Added</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody></tbody>
</table>

<div class="row mb-3 mt-3">
    <div class="col w-100"><a class="btn btn-success w-100" asp-controller="GamesManager" asp-action="GameForm">Добавить игру</a></div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            var t = $('#tblCarousel').DataTable({
                ajax: {
                    url: "/api/games",
                    dataSrc:""
                },
                columnDefs: [ {
                    searchable: false,
                    orderable: false,
                    targets: 0
                } ],
                order: [[ 1, 'asc' ]],
                columns: [
                    {
                        data: "id"
                    },
                    {
                        data: "name",
                        render: function (data, type, game) {
                            return "<a href='/admin/GamesManager/GameForm/" + game.id + "' class=''>"  + data + "</a>";
                        }
                    },
                    {
                        data: "originalPrice"
                    },
                    {
                        data: "finalPrice"
                    },
                    {
                        data: "quantity"
                    },
                    {
                        data: "dateAdded"
                    },
                    {
                        data: "id",
                        render: function(data) {
                            return "<button class='btn btn-danger js-delete w-100' data-game-id=" +
                                data +
                                "> Delete <i class='fa fa-trash' aria-hidden='true'></i></button>";
                        }
                    }
                    ]
            });

            t.on( 'order.dt search.dt', function () {
                t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                    cell.innerHTML = i+1;
                } );
            }).draw();



            $('#tblCarousel').on('click', '.js-delete', function () {
                var button = $(this);

                bootbox.confirm("Are you sure?",
                    function(result) {
                        if (result) {
                            $.ajax({

                                url: "/api/games/" + button.attr("data-game-id"),
                                method: "DELETE",
                                success: function() {
                                    button.parents("tr").remove();
                                }
                            });
                        }

                    });


            });

        });

    </script>


}